// You can find instructions for this file at http://www.treeview.net

//Environment variables are usually set at the top of this file.
USETEXTLINKS = 1
STARTALLOPEN = 0
USEFRAMES = 0
USEICONS = 0
WRAPTEXT = 1
PERSERVESTATE = 0
HIGHLIGHT = 1

foldersTree = gFld("<b>工程編碼</b>", "javascript:undefined")
  aux0 = insFld(foldersTree, gFld("00契約要項", "#.htm"))
    insDoc(aux0, gLnk("R", "001營建費用", "#.htm"))
    insDoc(aux0, gLnk("R", "002其他", "#.htm"))
  aux1 = insFld(foldersTree, gFld("01假設", "#.htm"))
    insDoc(aux1, gLnk("R", "001整地放樣", "#.htm"))
    insDoc(aux1, gLnk("R", "002鷹架防護", "#.htm"))
	insDoc(aux1, gLnk("R", "003工務所", "#.htm"))
	insDoc(aux1, gLnk("R", "004圍籬", "#.htm"))
	insDoc(aux1, gLnk("R", "005拆除及打除", "#.htm"))
  aux2 = insFld(foldersTree, gFld("02基礎", "#.htm"))
  	aux2a = insFld(aux2, gFld("001地質改良", "#.htm"))
	aux2a = insFld(aux2, gFld("002鋼製樁類", "#.htm"))
	aux2a = insFld(aux2, gFld("003場鑄樁", "#.htm"))
  	aux2c = insFld(aux2, gFld("004連續壁", "#.htm"))
	aux2c = insFld(aux2, gFld("005安全支撐", "#.htm"))
	aux2c = insFld(aux2, gFld("006觀測系統", "#.htm"))
	aux2c = insFld(aux2, gFld("007土方", "#.htm"))
	aux2c = insFld(aux2, gFld("008抽排水", "#.htm"))
  aux3 = insFld(foldersTree, gFld("03結構體", "hello.htm"))
	aux3a = insFld(aux3, gFld("001混凝土", "#.htm"))
	aux3a = insFld(aux3, gFld("002竹節鋼筋", "#.htm"))
	aux3a = insFld(aux3, gFld("003鋼結構", "#.htm"))
  	aux3c = insFld(aux3, gFld("004模板", "#.htm"))
  aux4 = insFld(foldersTree, gFld("04隔間牆", "hello.htm"))
	aux4a = insFld(aux4, gFld("001砌磚", "#.htm"))
	aux4a = insFld(aux4, gFld("002輕隔間", "#.htm"))
	aux4a = insFld(aux4, gFld("003搗擺", "#.htm"))
  	aux4c = insFld(aux4, gFld("004淋浴間", "#.htm"))	
  aux5 = insFld(foldersTree, gFld("05防水處理", "hello.htm"))
	aux5a = insFld(aux5, gFld("001樹脂砂漿", "#.htm"))
	aux5a = insFld(aux5, gFld("002防水處理", "#.htm"))
	aux5a = insFld(aux5, gFld("003PU防水層", "#.htm"))
  aux6 = insFld(foldersTree, gFld("06地坪裝修", "javascript:undefined"))
		aux61=insDoc(aux6, gFld( "001整體粉光", "#.htm"))
		insDoc(aux61, gLnk("R", "1地坪整體粉光", "#.htm"))
		insDoc(aux61, gLnk("R", "2鋼梯踏步粉光", "#.htm"))
		insDoc(aux61, gLnk("R", "3地坪機械磨光", "#.htm"))
		aux62=insDoc(aux6, gFld( "002水泥粉光", "hello.htm"))
		insDoc(aux62, gLnk("R", "1地坪1:3水泥粉刷", "#.htm"))
		insDoc(aux62, gLnk("R", "2浴缸底水泥砂漿墊高", "#.htm"))
		insDoc(aux62, gLnk("R", "3地坪抿石子", "#.htm")) 
		insDoc(aux62, gLnk("R", "4地坪寒水石粉光", "#.htm"))
		insDoc(aux62, gLnk("R", "5地坪斬石子", "#.htm"))
		insDoc(aux62, gLnk("R", "6中間樁補孔地坪粉刷", "#.htm"))
		insDoc(aux62, gLnk("R", "7車道鋸齒狀粉光 (含寒水石)", "#.htm")) 
		insDoc(aux62, gLnk("R", "8車道鋸齒狀粉光 (含金剛砂)", "#.htm"))
		aux63=insDoc(aux6, gFld( "003耐磨塗料", "#.htm"))	
		insDoc(aux63, gLnk("R", "1自平式水泥砂漿硬化地坪  T=   mm", "#.htm"))	
		insDoc(aux63, gLnk("R", "2EPOXY地坪 t=3 mm", "#.htm"))	
		insDoc(aux63, gLnk("R", "3EPOXY地坪 t= 5 mm", "#.htm"))
  aux7 = insFld(foldersTree, gFld("07內牆裝修", "javascript:undefined"))
  	 aux71= insFld(aux7, gFld("001內牆水泥粉光", "#.htm"))
	 aux71= insFld(aux7, gFld("002內牆刷漆", "#.htm"))
	 aux71= insFld(aux7, gFld("003內牆壁磚", "#.htm"))
	 aux71= insFld(aux7, gFld("004內牆石材", "#.htm"))
//		insDoc(aux71, gLnk("R", "行動方案維護", "#.htm"))
//  		insDoc(aux71, gLnk("R", "行動方案核准", "#.htm"))
//  		insDoc(aux71, gLnk("R", "行動方案查詢", "#.htm"))
//  		insDoc(aux71, gLnk("R", "執行計畫維護", "#.htm"))
//  		insDoc(aux71, gLnk("R", "執行計畫核准", "#.htm"))
//  		insDoc(aux71, gLnk("R", "執行計畫查詢", "#.htm"))
//  	aux72= insFld(aux7, gFld( "執行情形填報", "hello.htm"))  		
//		insDoc(aux72, gLnk("R", "執行情形填報", "#.htm"))
//  		insDoc(aux72, gLnk("R", "執行情形核准", "#.htm))  	
//  	aux73= insFld(aux7, gFld( "結案管理", "hello.htm"))  			  		  		
//  		insDoc(aux73, gLnk("R", "行動方案結案", "#.htm"))
//  		insDoc(aux73, gLnk("R", "行動方案結案審核", "#.htm"))  		
//  	aux74= insFld(aux7, gFld( "彙整管理", "#.htm"))  			  		  		
//  		insDoc(aux74, gLnk("R", "彙整通知", "#.htm")) 			  		  		
//  		insDoc(aux74, gLnk("R", "彙整查詢", "#.htm"))
//  	aux75= insFld(aux7, gFld( "改善方案管理", "#.htm"))  			  		  		
//  		insDoc(aux75, gLnk("R", "執行情形填報", "#.htm")) 			  		  		
//  		insDoc(aux75, gLnk("R", "執行情形審核", "#.htm"))
//  		insDoc(aux75, gLnk("R", "改善方案查詢", "#.htm"))
//  aux8 = insFld(foldersTree, gFld("08平頂裝修", "javascript:undefined"))
// 	aux8a = insFld(aux8, gFld("001整體粉光", "javascript:undefined"))
//    insDoc(aux8a, gLnk("R", "1地坪整體粉光", "#.htm"))
//    insDoc(aux8a, gLnk("R", "2鋼梯踏步粉光", "#.htm"))
//    insDoc(aux8a, gLnk("R", "3地坪機械磨光", "#.htm"))
//	aux9a = insFld(aux8, gFld("002水泥粉光", "javascript:undefined"))
//    insDoc(aux9a, gLnk("R", "1地坪1:3水泥粉刷", "#.htm"))
//    insDoc(aux9a, gLnk("R", "2浴缸底水泥砂漿墊高", "#.htm"))
//    insDoc(aux9a, gLnk("R", "3地坪抿石子", "#.htm"))
//    insDoc(aux9a, gLnk("R", "4地坪寒水石粉光", "#.htm"))
//  aux9 = insFld(foldersTree, gFld("09踢腳裝修", "javascript:undefined"))
//		insDoc(aux9, gLnk("R", "檔案上傳作業", "#.htm"))
//		insDoc(aux9, gLnk("R", "資料轉入作業", "#.htm"))
//		insDoc(aux9, gLnk("R", "轉入結果查詢", "#.htm"))

//Set this string if FolderTree and other configuration files may also be loaded in the same sessino
foldersTree.treeID = "t2" 
 